machine:
  environment:
      PATH: /home/ubuntu/miniconda/bin:$PATH

dependencies:
  override:
    - "rm -rf ~/virtualenvs"
    - "wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh"
    - "bash miniconda.sh -b -p $HOME/miniconda"
    - "hash -r"
    - "conda config --add channels conda-forge"
    - "conda config --set always_yes yes --set changeps1 no"
    - "conda install --file requirements/run.txt"

test:
  override:
    - py.test -v ./tests/
